### PR TITLE
Livability score display 

### PR DESCRIPTION
**Pull request by aware91**
# [Livability Score Display](#Link_to_corresponding_Trello_card)

## Files Modified:

-Map.js
-navBar.js

## Files Added:

-CityScr.js
-LivabilityLandingPage.js
-LivabilityCSS.css
-Locationscontext.js

## Details:

1. Set up a display for the livability score of a city when the user used the search bar.
2. Connected the search bar input text to the livability display using context.
3. Set a conditional statement for when there is no data base request.

## Committed Features:

1. Set up livability test data and test it.
2. Added the 5 livability score pages and have hardcoded data and tested
3. added livability to map and added it to fix the bottom left
4. backend Heroku locations BE is set up endpoints are working
5. started logical operator and have it working with  true and false example
6. added Mapbox API JSON and able to pull up data
7. set up location to come from Map.js to CityScr.js from location context
8. added condition statement and think it is working have to wait for backend to update the database
9. added heart for favorites button and changed city name to location of city typed
10. Set up conditional statement to be true

### CODE REVIEW

**Review by schang1146 — DISMISSED** [review]
Demo'd to me earlier. Looks good so far.

**Review by shanejeremich — DISMISSED** [review]
I like the way you set up the LivabilityScore, looks great.

**Review by schang1146 — APPROVED** [review]
Looks like merge conflicts are fixed. Awesome work.

**Comment by sjeremich23** [comment]
Good job on fixing the merge conflicts

**Review by shanejeremich — APPROVED** [review]
Good job on fixing the merge conflicts

**Pull request merged**
